### ISSUE TITLE
Company_Collector

### ISSUE THREAD

**Issue by chandutr** [dmatarinl/Company_collector#1]
(2002,Can’t connect to server on ‘localhost’(10061)”) , what should I do to overcome this?? Please Reply

**Comment by dmatarinl** [comment]
Hi @chandutr, 

This code is pretty simple, so I will assume that the problem lies in the use of the port. This error can appear for several reasons, the first thing that comes to mind is to ask, why you use that port? I recommend using more typical ports such as 8000 or 8080, still, if you want to keep using that port, check if the port that you're using is usable and not already occupied.

David.

> (2002,Can’t connect to server on ‘localhost’(10061)”) , what should I do to overcome this?? Please Reply
